#!/bin/bash
# tests/ci_report.sh — CI Report Generator
# Generates a human-readable markdown summary of the CI pipeline run.
# Usage: ./tests/ci_report.sh > ci_report.md

set -euo pipefail

COMMIT_SHA="${GITHUB_SHA:-$(git rev-parse --short HEAD 2>/dev/null || echo 'local')}"
BRANCH="${GITHUB_REF_NAME:-$(git branch --show-current 2>/dev/null || echo 'unknown')}"
DATE=$(date -u +"%Y-%m-%d %H:%M UTC")

echo "# Upsilon Battle — CI Report"
echo ""
echo "| Field | Value |"
echo "|---|---|"
echo "| **Date** | $DATE |"
echo "| **Commit** | \`$COMMIT_SHA\` |"
echo "| **Branch** | \`$BRANCH\` |"
echo ""

# --- E2E Scenario Results ---
echo "## E2E Customer Scenarios"
echo ""
BATTLE_LOG_DIR="upsiloncli/tests/logs"
if [ -d "$BATTLE_LOG_DIR" ]; then
    echo "| Scenario | Result |"
    echo "|---|---|"
    for logfile in "$BATTLE_LOG_DIR"/*.log; do
        if [ ! -f "$logfile" ]; then continue; fi
        NAME=$(basename "$logfile" .log)
        # Unified success method: check for the marker appended by the runner
        if grep -q "\[SCENARIO_RESULT: PASSED\]" "$logfile"; then
            echo "| \`$NAME\` | ✅ PASS |"
        else
            echo "| \`$NAME\` | ❌ FAIL |"
        fi
    done
else
    echo "> [!NOTE]"
    echo "> Scenario log directory not found. E2E tests may not have run."
fi
echo ""

# --- BRD Compliance ---
echo "## BRD Compliance Checks"
echo ""
echo "| ID | Requirement | ATD Atom | Status |"
echo "|---|---|---|---|"

# Helper function to check and report BRD compliance.
# Resolves the best available aggregate log for a token:
#   1. e2e_<token>.log        (exact match — scenario was not renamed)
#   2. e2e_<token>_with_2.log (scenario was renamed with the _with_2 suffix)
# The PASSED check is performed on whichever file is found first.
# Per-bot _Bot-N files are never consulted.
check_brd() {
    local cr_id=$1
    local name=$2
    local atom=$3
    local token=$4

    local exact_log="$BATTLE_LOG_DIR/e2e_${token}.log"
    local with2_log="$BATTLE_LOG_DIR/e2e_${token}_with_2.log"

    local resolved_log=""
    if [ -f "$exact_log" ]; then
        resolved_log="$exact_log"
    elif [ -f "$with2_log" ]; then
        resolved_log="$with2_log"
    fi

    if [ -n "$resolved_log" ] && grep -q "\[SCENARIO_RESULT: PASSED\]" "$resolved_log"; then
        echo "| **$cr_id** | $name | \`$atom\` | ✅ |"
    else
        echo "| **$cr_id** | $name | \`$atom\` | ❌ |"
    fi
}

# Mapping all 17 scenarios
check_brd "CR-01" "New Player Onboarding" "[[uc_player_registration]]" "customer_onboarding"
check_brd "CR-02" "Player Login & Session" "[[uc_player_login]]" "customer_login"
check_brd "CR-03" "Character Reroll Mechanics" "[[us_character_reroll]]" "character_reroll"
check_brd "CR-04" "Matchmaking PvE (Instant)" "[[uc_matchmaking]]" "matchmaking_pve_instant"
check_brd "CR-05" "Matchmaking PvP (Queue)" "[[uc_matchmaking]]" "matchmaking_pvp_queue"
check_brd "CR-06" "Combat Turn Management" "[[uc_combat_turn]]" "combat_turn_management"
check_brd "CR-07" "Friendly Fire Prevention" "[[rule_friendly_fire]]" "friendly_fire_prevention"
check_brd "CR-08" "Match Resolution (Standard)" "[[uc_match_resolution]]" "match_resolution_standard"
check_brd "CR-09" "Match Resolution (Forfeit)" "[[uc_match_resolution]]" "match_resolution_forfeit"
check_brd "CR-10" "Progression (Post-Win)" "[[uc_progression_stat_allocation]]" "progression_post_win"
check_brd "CR-11" "Progression Constraints" "[[rule_progression]]" "progression_constraints"
check_brd "CR-12" "Leaderboard Viewing" "[[us_leaderboard_view]]" "leaderboard_viewing"
check_brd "CR-13" "Password Policy" "[[rule_password_policy]]" "password_policy"
check_brd "CR-14" "GDPR Data Portability" "[[api_profile_export]]" "gdpr_portability"
check_brd "CR-15" "Admin User Management" "[[uc_admin_user_management]]" "admin_user_management"
check_brd "CR-16" "Session Timeout Handling" "[[req_security_token_ttl]]" "session_timeout"
check_brd "CR-17" "API Self-Discovery" "[[requirement_customer_api_first]]" "api_discovery"
check_brd "CR-18" "Admin Full Lifecycle" "[[uc_admin_login]]" "admin_full_lifecycle"
check_brd "CR-19" "Admin History Management" "[[uc_admin_history_management]]" "admin_history_management"
check_brd "CR-20" "Credit Economy (damage)" "[[rule_credit_earning_damage]]" "credit_economy"

echo ""
echo "---"
echo "*Generated by \`tests/ci_report.sh\` at $DATE*"
