#!/bin/bash
# tests/unit_report.sh — Unit Test Report Generator
# Generates a human-readable markdown summary of unit test results.
# Usage: ./tests/unit_report.sh > unit_report.md

set -euo pipefail

COMMIT_SHA="${GITHUB_SHA:-$(git rev-parse --short HEAD 2>/dev/null || echo 'local')}"
DATE=$(date -u +"%Y-%m-%d %H:%M UTC")

echo "# Upsilon — Unit Test Report"
echo ""
echo "| Field | Value |"
echo "|---|---|"
echo "| **Date** | $DATE |"
echo "| **Commit** | \`$COMMIT_SHA\` |"
echo ""

# --- Go Test Results ---
echo "## Go Unit Tests"
echo ""
GO_RESULTS="go-test-results.json"
if [ -f "$GO_RESULTS" ]; then
    PASS_COUNT=$(grep -c '"Action":"pass"' "$GO_RESULTS" || true)
    FAIL_COUNT=$(grep -c '"Action":"fail"' "$GO_RESULTS" || true)
    SKIP_COUNT=$(grep -c '"Action":"skip"' "$GO_RESULTS" || true)

    if [ "$FAIL_COUNT" -gt 0 ]; then
        echo "| Suite | Passed | Failed | Skipped | Result |"
        echo "|---|---|---|---|---|"
        echo "| Go Modules | $PASS_COUNT | $FAIL_COUNT | $SKIP_COUNT | ❌ FAIL |"
        echo ""
        echo "<details><summary>Failed Tests</summary>"
        echo ""
        echo '```'
        grep '"Action":"fail"' "$GO_RESULTS" | head -20
        echo '```'
        echo "</details>"
    else
        echo "| Suite | Passed | Skipped | Result |"
        echo "|---|---|---|---|"
        echo "| Go Modules | $PASS_COUNT | $SKIP_COUNT | ✅ PASS |"
    fi
else
    echo "> [!WARNING]"
    echo "> Go test results file (\`$GO_RESULTS\`) not found."
fi
echo ""
echo "---"
echo "*Generated by \`tests/unit_report.sh\` at $DATE*"
